name: landescapes
favicon: null
layout_spectrum: 0.8367487653158605
typography_spectrum: 0.7076139375567436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.45804947637952864
  lightness: 0.6257685669697821
  saturation: 0.6318170407321304
  rhythmicContrast: 0.623872552299872
purpose: []
